# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_lacunarity <- function(mat, w_vec, fun, mode, ncores = 1L, display_progress = FALSE) {
    .Call(`_spatLac_rcpp_lacunarity`, mat, w_vec, fun, mode, ncores, display_progress)
}

